### ISSUE TITLE
[feat] Add domain name and https support

### ISSUE THREAD

**Issue by wonhyeongseo** [42Gyeongsan-side-project/server#9]
### 기능 요청

안녕하세요! 도메인 네임과 https를 지원하도록 api를 업데이트해주세요.

### 동기

iOS을 비롯한 모바일에서는 https와 도메인네임이 설정되어야 api를 사용할 수 있습니다.

### 당신의 기여

Ngrok, Let's encrypt 를 함께 살펴볼 수 있습니다.

**Comment by joonwan** [comment]
### 배경

Https 연결을 하여 데이터를 주고 받기위 ngrok 을 사용합니다. 

### 사용법

SSH 로 터미널에 접속한 뒤 아래 명령어를 작성해야 합니다.

```
 ngrok http localhost:8080
```
위 명령어 실행시 아래와 같이 ngrok이 실행됩니다.
<img width="643" alt="스크린샷 2024-04-29 오후 1 50 55" src="https://github.com/42Gyeongsan-side-project/server/assets/111417356/bb3c8296-afe9-46d6-9886-a3571b722b44">

아래 ```Forwarding``` 뒤를 보면 https 로 시작하는 경로가 보입니다.이 주소를  ```base url``` 로 사용하고 상황에 맞는 end point 를 사용하여 요청을 할 경우 포트 포워딩이 되어 서버측에 요청이 전달 됩니다.

### 주의

터미널을 닫을 경우 ngrok 서버가 종료됩니다. 따라서 테스트 할 경우 계속 ngrok 을 켜놓는 것을 추천합니다.

**Comment by wonhyeongseo** [comment]
NCP의 API Gateway를 통해 해결됐습니다. 아키텍처 구성을 3 Tier Web App으로 할 지 생각해볼게요. 감사합니다!
